[workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[system-requirements]
cuda = "12"


[dependencies]
python = "*"
cuda = "*"
tensorflow = "*"
scipy-stubs = "*"
matplotlib = "*"
seaborn = "*"
ipdb = "*"
jupyterlab = "*"
scikit-learn = "*"
line_profiler = ">=4.2.0,<5"
pandas = "*"
pandas-stubs = "*"
wandb = "*"


[pypi-dependencies]
ytm = { path = ".", editable = true }
medmnist = "*"
microsoft-python-type-stubs = { git = "https://github.com/microsoft/python-type-stubs.git" }

