[workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[system-requirements]
cuda = "12"

[dependencies]
python = ">=3.11"
jupyterlab = ">=4.4.4,<5"
ipdb = ">=0.13.13,<0.14"
line_profiler = ">=4.2.0,<5"
cuda = ">=12.9.1,<13"

[pypi-dependencies]
ytm = { path = ".", editable = true, extras = ["examples"] }
